Mudanças nas semântica do HTML e alteração do FW CSS
cuducos/pwned-antifas pull request #14
Opened 2020-06-10 20:39 UTC by nalmeida

Fiz uma sugestão de alteração de mudança do framework CSS do Bootstrap para um que eu criei, chamado Modesto. Basicamente ele só normaliza os elementos nativos e parte do proncípio "classless" ou seja, é só criar um HTML semântico que a coisa funciona. 

Além disso modesto gzipado pesa 2.18Kb equanto o Bootstrap na casa dos 24Kb.

Criei pra usar em uns projetos meus, que são basicamente uma página como o `pwned-antifas`. Se acharem boa ideia, ficarei feliz em contribuir.

2020-06-10 20:50 UTC, cuducos commented
Oi @nalmeida, fico feliz com o PR, mas tenho dúvidas sobre o quanto ele realmente ajuda o projetinho aqui. Algumas dúvidas para a gente refletir:

**Dúvidas**

* Teira que alterar também as [classes ou tags geradas pelo Elm](https://github.com/cuducos/pwned-antifas/blob/master/src/View.elm)?

**Pontos negativos**

* Não acho legal em um projeto aberto substituir o Bootstrap por um framework que vai aumentar a curva de entrada de novos contribuidores (por exemplo, procurei por Modesto CSS e nem a documentação aparece nos primeiro resultados da busca)… isso tem impacto na manutenção do projeto.

**Pontos positivos**

* Arquivo menor


Para mim, essa conta ainda não fecha. O que acham?

2020-06-10 22:11 UTC, nalmeida commented
Oi @cuducos, realmente utilizar o Bootstrap que tem ampla documentação facilita muito a utilização por outros contribuidores. 

Uma coisa que acho uma vantagem do Modesto é o fato de nem precisar estilizar nada, mais escrever o HTML mesmo e o resultado já parecer "diagramado". Nesse caso, a documentação é basicamente a [página de exemplo](https://modesto.netlify.app/exemplo.html).

Para essas classes geradas pelo Elm, seria realmente necessário criar um "estilo" para cada uma delas. Criei uma classe genérica de `alert` que poderia ser usada para o caso específico do projeto.

Sinta-se à vontade para declinar o PR. De qualquer forma, ainda recusando o "CSS" achei que o HTML ficou melhor. Transformando pontos que eram `<p>` em listas, havia um `<em>` não fechado dentro de um `h2`. Se achar válido, abro um outro PR só com o HTML.

_PS.: "Sigo" seu perfil no Twitter e acho um BAITA trabalho de ativismo digital o que você e outros contribuidores fazem! Esse projeto mesmo é muito importante para o momento que estamos vivendo. Já deixo aqui meus cumprimentos pela iniciativa! E pela velocidade em que foi efito!_

2020-06-10 23:45 UTC, cuducos requested changes
Excelentes comentários : )

Creio que para a gente aprovar esse PR, então, podemos fazer duas coisas:

- [ ] Fazer as alterações necessárias para o HTML gerado pelo Elm ser estilizado
- [ ] Adicionar no HTML (no comentário antes de importar o Modesto CSS) o link para a documentação do projeto (acho https://modesto.netlify.app/ melhor do que a página de exemplo para esse fim, o que acham?)

2020-06-12 13:14 UTC, nalmeida commented
Oi @cuducos,

Implementei as classes de alert, coloquei um link do gif animado para abrir ele mesmo em uma nova janela (para uma pessoa no mobile conseguir dar zoom, por exemplo) e o comentário sobre a documentação do FW.

Segue baixo um print de como as telas ficaram (forçando os alerts na tela para vocês conferirem).

Veja se faz sentido mudar para o Modesto ou se continuar com o Bootstrap vai manter a vida dos contribuidores mais fácil. O projeto é tão legal que se não tivesse CSS nenhum ainda seria purou ouro!!!

---

![desktop](https://user-images.githubusercontent.com/200209/84505951-fd1e9a80-ac94-11ea-93ad-9a67d22fec9c.png)

---

![mobile](https://user-images.githubusercontent.com/200209/84506009-0f98d400-ac95-11ea-8cac-5c84561529b8.png)

2020-06-15 19:57 UTC, merged